# Generated by Django 4.1.7 on 2023-05-01 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram ', 'Instagram '), ('linkedin', 'linkedin'), ('GitHub ', 'GitHub'), ('GitLab ', 'GitLab'), ('Website', 'Website')], max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('prop_type', models.CharField(blank=True, max_length=4, null=True)),
                ('Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.person')),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
