# Generated by Django 4.1.7 on 2023-05-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_socialweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialweb',
            name='prop_type',
        ),
    ]
