# Generated by Django 4.1.7 on 2023-03-04 09:40

from django.db import migrations, models
import django.db.models.deletion
import usersapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default=1, max_length=50)),
                ('code', models.CharField(default=1, max_length=5)),
                ('currency', models.CharField(default=1, max_length=5)),
                ('currency_name', models.CharField(default=1, max_length=50)),
                ('currency_symbol', models.CharField(default=1, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='state', max_length=50)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_state', to='usersapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='city', max_length=50)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='usersapp.country')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usersapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('fullname', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, default='images/users/person.png', null=True, upload_to=usersapp.models.upload_to_u)),
                ('type_user', models.IntegerField(blank=True, default=1, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_publish', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_token', models.CharField(max_length=250)),
                ('city', models.ForeignKey(default=102874, on_delete=django.db.models.deletion.CASCADE, related_name='city_user', to='usersapp.city')),
                ('country', models.ForeignKey(default=194, on_delete=django.db.models.deletion.CASCADE, related_name='country_user', to='usersapp.country')),
                ('state', models.ForeignKey(default=2849, on_delete=django.db.models.deletion.CASCADE, related_name='state_user', to='usersapp.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
