# Generated by Django 4.1.7 on 2023-03-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(default='+965', max_length=5),
        ),
    ]
