# Generated by Django 4.1.7 on 2023-04-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_language_keylang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keylang',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='usersapp.language'),
        ),
    ]
