# Generated by Django 4.1.7 on 2023-04-15 09:39

from django.db import migrations, models
import usersapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_keylang_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_image',
            field=models.ImageField(blank=True, default='images/users/grid.png', null=True, upload_to=usersapp.models.upload_to_u),
        ),
    ]
