# Generated by Django 4.1.7 on 2023-04-12 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import proprety.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_keylang_lang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proprety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proprety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('prop_type', models.CharField(blank=True, choices=[('Rent', 'Rent'), ('Sael', 'Sael')], max_length=4, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=15, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('areaunit', models.CharField(blank=True, choices=[('Suqare Meter', 'Suqare Meter'), ('Suqare Feet', 'Suqare Feet'), ('Suqare Yard', 'Suqare Yard'), ('Kanal', 'Kanal'), ('Marla', 'Marla')], max_length=255, null=True)),
                ('bedrooms', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=255, null=True)),
                ('baths', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('living_room', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('cinema', models.BooleanField(default=False)),
                ('conference', models.BooleanField(default=False)),
                ('swimming_poll', models.BooleanField(default=False)),
                ('maid_room', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('linkurl', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('is_publish', models.BooleanField(default=True)),
                ('view', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_cat', to='proprety.category')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_city', to='usersapp.city')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_country', to='usersapp.country')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_state', to='usersapp.state')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_subcat', to='proprety.subcategory')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='propretyimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprety_image', models.ImageField(max_length=256, null=True, upload_to=proprety.models.upload_to_Prop)),
                ('is_main', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('proprety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_image', to='proprety.proprety')),
            ],
        ),
        migrations.CreateModel(
            name='propretyfave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fav', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('proprety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_fav', to='proprety.proprety')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proprety_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='countrypropretyads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listcountry', models.CharField(blank=True, max_length=250, null=True)),
                ('liststate', models.CharField(blank=True, max_length=250, null=True)),
                ('listcity', models.CharField(blank=True, max_length=250, null=True)),
                ('proprety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprety1_ads', to='proprety.proprety')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propretyads1_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
