# Generated by Django 4.1.7 on 2023-03-06 09:45

import automotive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=automotive.models.upload_to_b)),
                ('is_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=automotive.models.upload_to_c)),
                ('is_home', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcatgoriess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=automotive.models.upload_to_c)),
                ('cats', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automotive.categories')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=automotive.models.upload_to_b)),
                ('brands', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automotive.brands')),
            ],
        ),
    ]
