# Generated by Django 4.1.7 on 2023-03-09 10:47

import automotive.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapp', '0001_initial'),
        ('automotive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=125, null=True)),
                ('auto_type', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=4, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('kilometers', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=125, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=125, null=True)),
                ('body_condition', models.CharField(blank=True, choices=[('Perfect Inside and Outside', 'Perfect Inside and Outside'), ('No accidents, very few faults', 'No accidents, very few faults'), ('Bit of wear tear, all repaired', 'Bit of wear tear, all repaired'), ('Lots of wear tear to the body', 'Lots of wear tear to the body')], max_length=255, null=True)),
                ('inside_out', models.CharField(blank=True, choices=[('Perfect Inside and Outside', 'Perfect Inside and Outside'), ('Minor faults, all fixed', 'Minor faults, all fixed'), ('Major faults fixed, small remains', 'Major faults fixed, small remains'), ('Ongoing minor major faults', 'Ongoing minor major faults')], max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('verification_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=255, null=True)),
                ('transmission_type', models.CharField(blank=True, choices=[('Manual Transmission', 'Manual Transmission'), ('Automatic Transmission', 'Automatic Transmission')], max_length=64, null=True)),
                ('door', models.CharField(blank=True, choices=[('2 doors', '2 doors'), ('3 doors', '3 doors'), ('4 doors', '4 doors'), ('5+ doors', '5+ doors')], max_length=64, null=True)),
                ('power', models.CharField(blank=True, choices=[('Less than 150 HP', 'Less than 150 HP'), ('150- 200 HP', '150- 200 HP'), ('200- 300 HP', '200- 300 HP'), ('300- 400 HP', '300- 400 HP'), ('400- 500 HP', '400- 500 HP'), ('Other', 'Other')], max_length=64, null=True)),
                ('specs', models.CharField(blank=True, choices=[('European Specs', 'European Specs'), ('GCC Specs', 'GCC Specs'), ('Japanese Specs', 'Japanese Specs'), ('North American Specs', 'North American Specs'), ('Other', 'Other')], max_length=64, null=True)),
                ('cylinders', models.CharField(blank=True, max_length=64, null=True)),
                ('streeingside', models.CharField(blank=True, choices=[('Left Hand Side', 'Left Hand Side'), ('Right Hand Side', 'Right Hand Side')], max_length=64, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('linkurl', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='brandmodels',
            old_name='brands',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='subcatgoriess',
            old_name='cats',
            new_name='cat',
        ),
        migrations.RemoveField(
            model_name='brandmodels',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brands',
            name='is_home',
        ),
        migrations.AddField(
            model_name='brandmodels',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brands',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automotive.categories'),
        ),
        migrations.AddField(
            model_name='brands',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcatgoriess',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='automotiveimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automotive_image', models.ImageField(max_length=256, null=True, upload_to=automotive.models.upload_to_Auto)),
                ('is_main', models.DateTimeField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_image', to='automotive.automotive')),
            ],
        ),
        migrations.CreateModel(
            name='automotivefave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_fav', to='automotive.automotive')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='automotive',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_brand', to='automotive.brands'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='brandmodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_brandmodel', to='automotive.brandmodels'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_cat', to='automotive.categories'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_city', to='usersapp.city'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_country', to='usersapp.country'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_currency', to='usersapp.country'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_state', to='usersapp.state'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='subcat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotive_subcat', to='automotive.subcatgoriess'),
        ),
        migrations.AddField(
            model_name='automotive',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
