# Generated by Django 4.1.7 on 2023-03-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0002_automotive_rename_brands_brandmodels_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcatgoriess',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='automotive.categories'),
        ),
    ]
