# Generated by Django 4.1.7 on 2023-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0003_alter_subcatgoriess_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
