# Generated by Django 4.1.7 on 2023-03-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0004_automotive_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotiveimages',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
