# Generated by Django 4.1.7 on 2023-03-15 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automotive', '0005_alter_automotiveimages_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automotive',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='automotive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automotive',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automotive',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='countryautomotiveads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listcountry', models.CharField(blank=True, max_length=250, null=True)),
                ('liststate', models.CharField(blank=True, max_length=250, null=True)),
                ('listcity', models.CharField(blank=True, max_length=250, null=True)),
                ('automotive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automotive1_ads', to='automotive.automotive')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='automotiveads1_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
