# Generated by Django 4.1.7 on 2023-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0006_remove_automotive_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotivefave',
            name='is_fav',
            field=models.BooleanField(default=True),
        ),
    ]
