# Generated by Django 4.1.7 on 2023-03-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0007_automotivefave_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodels',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brandmodel', to='automotive.brands'),
        ),
    ]
