# Generated by Django 4.1.7 on 2023-03-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0008_alter_brandmodels_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
