# Generated by Django 4.1.7 on 2023-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0009_alter_brands_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='automotive',
            name='currency',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='brandmodels',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
