# Generated by Django 4.1.7 on 2023-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0010_automotive_phone_alter_automotive_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automotive',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
