# Generated by Django 4.1.7 on 2023-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0012_alter_automotive_kilometers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcatgoriess',
            options={'ordering': ['cat']},
        ),
        migrations.AddField(
            model_name='brands',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
