# Generated by Django 4.1.7 on 2023-04-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automotive', '0015_automotiveads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='automotiveads',
        ),
    ]
